const discord = require("discord.js")
exports.run = async (bot , message , args) => {
let emb = new discord.RichEmbed()
.setTitle("Help")
.setThumbnail("https://cdn.glitch.com/0be54144-726d-4e41-bcc5-9ea5c83277c7%2F20060409055611.gif?v=1594547914004")
.setDescription("Du hast den Hilfe Command aufgerufen")
.setColor("BLUE")
.addField("freunde" , "Zeigt dir andere Bots")
.addField("invite" , "So kannst du mich einladen ^.^")
.addField("ticket" , "öffnet ein Ticket!")
.addField("ADMIN COMMANDS" , "-------------------------")
.addField("sticket #ticket-name" , "Schließt das Ticket wieder") 
.setFooter(`${message.author.tag}` , message.author.avatarURL)
message.reply(emb)
}
